export { default as Inicio } from './Inicio';
export { default as Login } from './Login';
export { default as Profile } from './Profile';
export { default as Register } from './Register';
export { default as Tasks } from './Tasks';
export { default as TasksForm } from './TasksForm';
export { default as AcercaDe } from './acerca/AcercaDe';
export { default as usuarios } from './acerca/usuarios';
export { default as Dashboard } from './admin/Dashboard';
export * from './errors';
export * from './home';
export * from './loaders';
export { default as Noticia } from './noticias/Noticia';
export { default as NoticiasForm } from './noticias/NoticiasForm';
export { default as NoticiasMasInf } from './noticias/NoticiasMasInf';
export { default as NoticiasPublicas } from './noticias/NoticiasPublicas';
export { default as MapsRecorridos } from './recorridos/MapsRecorridos';
export { default as Recorridos } from './recorridos/Recorridos';
export { default as RecorridosForm } from './recorridos/RecorridosForm';
export { default as VerMasRecorridos } from './recorridos/VerMasRecorridos';
export { default as imgRecorridos } from './recorridos/imgRecorridos';
export { default as pruebademapa } from './recorridos/pruebademapa';
export { default as MapReportes } from './reportes/MapReportes';
export { default as ReportesMaps } from './reportes/ReportesMaps';
export { default as fromReportes } from './reportes/fromReportes';
// export { default as imagenes } from './slider/imagenes';
export * from './useFetch';
